### ISSUE TITLE
mosquitto_will_set_v5 not keep a copy of the properties

### ISSUE THREAD

**Issue by tph85666031** [eclipse-mosquitto/mosquitto#3095]
seems mosquitto_will_set_v5 not keep a copy of the properties, so the caller can not free the properties after calling this API.
this behavior is different from mosquitto_publish_v5.

**Comment by ckrey** [comment]
Yes, correct. But this is exactly as described in the API (see below). You shall not free the will properties except when the `mosquitto_will_set_v5` fails:

<img width="998" alt="Bildschirmfoto 2024-10-09 um 16 10 23" src="https://github.com/user-attachments/assets/fdd4cb2a-7190-448f-97b9-0c3cc6aa5629">

**Comment by ckrey** [comment]
@tph85666031 does this answer your question? Can you close the issue?

**Comment by tph85666031** [comment]
thanks
