### ISSUE TITLE
mosquitto-2.0.19 for x86 Windows installer not available

### ISSUE THREAD

**Issue by msmigielski** [eclipse-mosquitto/mosquitto#3120]
There is no mosquitto-2.0.19 for x86 Windows installer available on https://mosquitto.org/files/binary/win32/. 

Is it planned to add this?

**Comment by ralight** [comment]
Unless there's a compelling reason, no. If you do have a compelling reason, please go ahead and explain and I will take it into consideration.

The only reason I can see is if you're running on Windows 10 32-bit. As I understand it, Microsoft stopped allowing that as an install option four years ago.

**Comment by msmigielski** [comment]
We still have some older devices running on a 32-bit OS. I need to update the Mosquitto library to get support for MQTT 5.0 and multithreading. I saw in the changelog that multithreading support was restored in version 2.0.19.

It would be great to have an out-of-the-box installer.

**Comment by ralight** [comment]
Could you test out the installer available here please? https://github.com/eclipse/mosquitto/actions/runs/11182870291

**Comment by msmigielski** [comment]
I checked it. Unfortunately, this is the installer for the 64-bit version. The build log shows that the x64 toolchain was used.

**Comment by santoshks68** [comment]
I too would be interested in having an x86 Windows installer for Mosquitto

**Comment by ralight** [comment]
This is now available from the download page.
