### ISSUE TITLE
Multiple AUTH packet exchange usage

### ISSUE THREAD

**Issue by domasgim** [eclipse-mosquitto/mosquitto#3145]
## Description

I am trying to create a mosquitto plugin that utilizes AUTH packets to implement a custom authentication mechanism. I have managed to create both a sample mosquitto broker plugin and client application. I want to extend it by utilizing AUTH packet exchange before the server sending CONNACK. I already managed to send `MOSQ_ERR_AUTH_CONTINUE` from the broker to the client and can already see that the client received the AUTH packet by the following log message  
```
[Level 16]: Client (null) sending CONNECT
[Level 16]: Client (null) received AUTH
```
The question is how to continue sending AUTH packets from the client to the broker if it receives `MOSQ_ERR_AUTH_CONTINUE`? After reading the mosquitto library reference I could not find any documentation regarding this part.  

AUTH exchange reference: https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Enhanced_authentication   

_"The Client and Server exchange AUTH packets as needed until the Server accepts the authentication by sending a CONNACK with a Reason Code of 0. If the acceptance of the authentication requires data to be sent to the Client, it is sent in the Authentication Data. "_

**Comment by ralight** [comment]
I'm afraid this isn't possible in the 2.0.x release. I've just pushed some code to the `develop`  branch that will let you do extended auth in the client library.
