### ISSUE TITLE
Is test.mosquitto.org down?

### ISSUE THREAD

**Issue by wunaidage** [eclipse-mosquitto/mosquitto#3173]
I know here might not be the best place to ask but i cannot find other places. My gadgets cannot connect to the broker, nor my phone's MQTTool.

**Comment by jamesquilty** [comment]
FWIW, I'm also unable to connect to `test.mosquitto.org:1883`, tried via separate networks and devices. The server responds to `ping` but not to socket connections on port 1883. Didn't try any others.

**Comment by jamesquilty** [comment]
@wunaidage it's back up (has been for a few days) so it's probably best to close this Issue (if you have sufficient privileges).
